gesdinet_jwt_refresh_token:
    ttl: 2592000
    user_identity_field: username
    user_provider: security.user.provider.concrete.app_user_provider

# gesdinet_jwt_refresh_token:
#     user_identity_field: email