monolog:
    handlers:
        security:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/security/%kernel.environment%.log'
            channels: [security]
            max_files: 365

        doctrine:
            level:    debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/doctrine/%kernel.environment%.log'
            channels: [doctrine]
            max_files: 365

        event:
            level: debug
            type:     rotating_file
            path:     '%kernel.logs_dir%/event/%kernel.environment%.log'
            channels: [event]
            max_files: 365

        request:
            action_level: request
            type:     rotating_file
            path:     '%kernel.logs_dir%/request/%kernel.environment%.log'
            channels: [request]
            max_files: 365

        main:
            level: debug
            type:  rotating_file
            path:  '%kernel.logs_dir%/%kernel.environment%.log'
            channels: ['!security', '!doctrine', '!event', '!request']
            max_files: 365
            # handler:      deduplicated

        # deduplicated:
        #     type:    deduplication
        #     handler: mailer
        # mailer:
        #     type:       swift_mailer
        #     from_email: '%env(LOG_FROM_EMAIL)%'
        #     to_email:   '%env(LOG_TO_EMAIL)%'
        #     subject:    'FA-COUNTING - [%kernel.environment%]: An Error Occurred! %%message%%'
        #     level:      debug
        #     formatter:  monolog.formatter.html
        #     content_type: text/html